/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{vue,js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    colors: {
      transparent: "transparent",
      current: "currentColor",
      "on-secondary": "#ffffff",
      "on-primary-container": "#fefcff",
      "error-container": "#ffdad6",
      "background-layered": "#ffffff",
      secondary: "#595f69",
      "surface-container-lowest": "#ffffff",
      "surface-container-highest": "#e0e2ec",
      scrim: "rgba(2,9,19,0.5)",
      "surface-dim": "#d8d9e3",
      "inverse-primary": "#acc7ff",
      "on-tertiary-container": "#fffbff",
      "on-primary-fixed": "#001a40",
      "surface-container-low": "#f2f3fd",
      error: "#f04452",
      "grey-200": "#e5e8eb",
      "on-tertiary": "#ffffff",
      success: "#03b26c",
      "blue-light": "#e8f3ff",
      "on-tertiary-fixed": "#311300",
      "grey-50": "#f9fafb",
      "grey-900": "#191f28",
      "on-surface-variant": "#414754",
      surface: "#f9f9ff",
      "grey-100": "#f2f4f6",
      "inverse-on-surface": "#eff0fa",
      "on-secondary-fixed-variant": "#414751",
      tertiary: "#944600",
      "surface-bright": "#f9f9ff",
      "on-tertiary-fixed-variant": "#743500",
      "tertiary-fixed-dim": "#ffb689",
      "secondary-container": "#dae0ec",
      "tertiary-container": "#ba5900",
      "on-primary": "#ffffff",
      "blue-hover": "#2272eb",
      "surface-variant": "#e0e2ec",
      "on-secondary-container": "#5d636e",
      "surface-container": "#ecedf7",
      "tertiary-fixed": "#ffdbc8",
      outline: "#727785",
      "inverse-surface": "#2d3038",
      primary: "#0059b9",
      "outline-variant": "#c1c6d6",
      "surface-tint": "#005bbe",
      "on-error-container": "#93000a",
      "primary-fixed": "#d7e2ff",
      "on-primary-fixed-variant": "#004491",
      "on-surface": "#181c23",
      "secondary-fixed": "#dde3ef",
      "on-error": "#ffffff",
      "grey-400": "#b0b8c1",
      warning: "#fe9800",
      "on-secondary-fixed": "#161c25",
      background: "#f9f9ff",
      "secondary-fixed-dim": "#c1c7d3",
      "surface-container-high": "#e6e8f2",
      "on-background": "#181c23",
      "primary-fixed-dim": "#acc7ff",
      "primary-container": "#1071e5",
      "grey-600": "#6b7684",
      red: "#f04452",
      yellow: "#fe9800",
      blue: "#0059b9",
      navy: "#181c23",
      teal: "#03b26c",
      white: "#ffffff",
    },
    extend: {
      fontFamily: {
        "display-large": ["Work Sans", "sans-serif"],
        "number-display": ["Work Sans", "sans-serif"],
        "heading-lg": ["Work Sans", "sans-serif"],
        subtitle: ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        body: ["Inter", "sans-serif"],
        heading: ["Work Sans", "sans-serif"],
        caption: ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "display-hero": ["Work Sans", "sans-serif"],
        display: ["Work Sans", "sans-serif"],
      },
      fontSize: {
        "display-large": ["26px", { lineHeight: "36px", fontWeight: "700" }],
        "number-display": ["30px", { lineHeight: "1.2", fontWeight: "700" }],
        "heading-lg": ["22px", { lineHeight: "30px", fontWeight: "700" }],
        subtitle: ["16px", { lineHeight: "24px", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        body: ["14px", { lineHeight: "22px", fontWeight: "400" }],
        heading: ["20px", { lineHeight: "28px", fontWeight: "600" }],
        caption: ["12px", { lineHeight: "18px", fontWeight: "400" }],
        "body-sm": ["13px", { lineHeight: "20px", fontWeight: "400" }],
        "display-hero": ["30px", { lineHeight: "40px", fontWeight: "700" }],
      },
      spacing: {
        md: "16px",
        base: "8px",
        "h-padding": "20px",
        xl: "32px",
        xs: "4px",
        lg: "24px",
        sm: "12px",
        "money-gap": "32px",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries"),
  ],
};
